/*
 * This Java source file was generated by the Gradle 'init' task.
 */


package gradleExample;

import ev3dev.actuators.LCD;
import lejos.hardware.lcd.*;






public class App {

    static GraphicsLCD screen;


    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        // screen = LCD.getInstance();

        // screen.clear();
        
        


        
        
    }
}
